name: Mint Pi Testnet Token

on:
  workflow_dispatch:  # handmatig starten in de Actions tab

jobs:
  mint:
    runs-on: ubuntu-latest

    env:
      ISSUER_SECRET: ${{ secrets.ISSUER_SECRET }}
      DISTRIBUTOR_SECRET: ${{ secrets.DISTRIBUTOR_SECRET }}
      TOKEN_CODE: BLASTX
      MINT_AMOUNT: 100000000000
      HOME_DOMAIN: toartje.github.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run token script
        run: node create_token.js
